<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\UsersStatsResource\Pages;
use App\Filament\Admin\Resources\UsersStatsResource\RelationManagers;
use App\Models\UsersStats;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class UsersStatsResource extends Resource
{
    protected static ?string $model = UsersStats::class;

    protected static ?string $navigationIcon = 'heroicon-o-chart-bar';

    protected static ?string $navigationGroup = 'Users Management';

    public static function getNavigationBadge(): ?string
    {
        return UsersStats::count();
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('guid')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('score')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('kills')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('downs')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('deaths')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('suicides')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('revives')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('headshots')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('melee_kills')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('grenade_kills')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('total_shots')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('hits')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('sacrifices')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('doors_purchased')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('distance_traveled')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('boards')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('drops')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('nuke_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('insta_kill_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('full_ammo_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('double_points_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('meat_stink_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('carpenter_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('fire_sale_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('zombie_blood_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('use_magicbox')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('use_pap')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_armorvest_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_quickrevive_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_rof_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_fastreload_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_flakjacket_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_additionalprimaryweapon_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_longersprint_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_deadshot_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_scavenger_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_finalstand_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_grenadepulldeath_drank')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('specialty_nomotionsensor')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('wallbuy_weapons_purchased')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('ammo_purchased')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('upgraded_ammo_purchased')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('power_turnedon')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('power_turnedoff')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('planted_buildables_pickedup')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('buildables_built')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('time_played_total')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('zdogs_killed')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('zdog_rounds_finished')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('zdog_rounds_lost')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('killed_by_zdog')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('screechers_killed')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('screecher_teleporters_used')
                    ->tel()
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('avogadro_defeated')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('killed_by_avogadro')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('prison_brutus_killed')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('buried_ghost_killed')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('tomb_mechz_killed')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('tomb_dig')
                    ->required()
                    ->numeric()
                    ->default(0),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('guid')
                    ->sortable(),
                Tables\Columns\TextColumn::make('name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('score')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('kills')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('downs')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('deaths')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('suicides')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('revives')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('headshots')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('melee_kills')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('grenade_kills')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_shots')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('hits')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('sacrifices')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('doors_purchased')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('distance_traveled')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('boards')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('drops')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('nuke_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('insta_kill_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('full_ammo_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('double_points_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('meat_stink_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('carpenter_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('fire_sale_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('zombie_blood_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('use_magicbox')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('use_pap')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_armorvest_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_quickrevive_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_rof_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_fastreload_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_flakjacket_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_additionalprimaryweapon_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_longersprint_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_deadshot_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_scavenger_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_finalstand_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_grenadepulldeath_drank')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('specialty_nomotionsensor')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('wallbuy_weapons_purchased')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('ammo_purchased')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('upgraded_ammo_purchased')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('power_turnedon')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('power_turnedoff')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('planted_buildables_pickedup')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('buildables_built')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('time_played_total')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('zdogs_killed')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('zdog_rounds_finished')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('zdog_rounds_lost')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('killed_by_zdog')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('screechers_killed')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('screecher_teleporters_used')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('avogadro_defeated')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('killed_by_avogadro')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('prison_brutus_killed')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('buried_ghost_killed')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('tomb_mechz_killed')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('tomb_dig')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListUsersStats::route('/'),
            'create' => Pages\CreateUsersStats::route('/create'),
            'edit' => Pages\EditUsersStats::route('/{record}/edit'),
        ];
    }
}
